"""Strict provider-neutral contracts for Block 3 trust boundaries."""

from __future__ import annotations

import math
from datetime import date, datetime, timedelta
from decimal import Decimal
from typing import Annotated, Literal

from pydantic import BaseModel, ConfigDict, Field, field_validator, model_validator

from ai_quant.model_calls import ModelCallMetadata

Identifier = Annotated[
    str,
    Field(min_length=3, max_length=160, pattern=r"^[a-z][a-z0-9]*(?:-[a-z0-9]+)*$"),
]
Sha256 = Annotated[str, Field(pattern=r"^[0-9a-f]{64}$")]
NonEmptyText = Annotated[str, Field(min_length=1, max_length=2_000)]

ClaimType = Literal["quantitative", "evidence", "limitation"]
ReferenceScope2Method = Literal["location_based", "market_based", "not_applicable"]
IssueCode = Literal[
    "unknown_metric",
    "unknown_evidence",
    "cross_run_reference",
    "free_numeric_literal",
    "metric_value_literal",
    "evidence_numeric_literal_unverified",
    "metric_placeholder_mismatch",
    "evidence_reference_mismatch",
    "generic_placeholder",
    "summary_placeholder",
    "unresolved_placeholder",
    "unsupported_risk_statement",
    "unsupported_period_alignment",
    "implicit_cross_domain_relation",
    "internal_status_token",
    "reference_value_mismatch",
    "reference_claim_key_mismatch",
    "reference_unit_mismatch",
    "reference_period_mismatch",
    "scope2_method_mismatch",
    "document_after_cutoff",
    "contradictory_source",
    "missing_required_field",
    "insufficient_coverage",
    "document_prompt_injection",
    "self_approval_attempt",
    "insufficient_trusted_inputs",
]
IssueSeverity = Literal["info", "warning", "error", "critical"]
AssessmentStatus = Literal["eligible_for_review", "review_required", "abstain"]
AssessmentReason = Literal[
    "validated_references",
    "blocking_validation_issues",
    "insufficient_trusted_inputs",
]
HumanDisposition = Literal["approved", "corrected", "rejected", "escalated"]
RunState = Literal["created", "generated", "validated", "pending_review", "finalized"]

IDENTIFIER_FAILURE_CODES: frozenset[IssueCode] = frozenset(
    {
        "unknown_metric",
        "unknown_evidence",
        "cross_run_reference",
        "metric_placeholder_mismatch",
        "evidence_reference_mismatch",
        "generic_placeholder",
        "summary_placeholder",
        "unresolved_placeholder",
        "reference_claim_key_mismatch",
    }
)
VALUE_FAILURE_CODES: frozenset[IssueCode] = frozenset(
    {
        "free_numeric_literal",
        "metric_value_literal",
        "evidence_numeric_literal_unverified",
        "reference_value_mismatch",
        "reference_unit_mismatch",
        "reference_period_mismatch",
        "scope2_method_mismatch",
    }
)


class StrictModel(BaseModel):
    """Base contract: immutable, strict and closed to unknown fields."""

    model_config = ConfigDict(extra="forbid", frozen=True, strict=True)


class MetricRecord(StrictModel):
    """Authoritative numeric record created only by Python from QuantAnalysis."""

    metric_id: Identifier
    run_id: Identifier
    metric_name: Identifier
    value: float
    unit: NonEmptyText
    horizon_or_frequency: NonEmptyText
    formula_version: NonEmptyText
    snapshot_id: Identifier

    @field_validator("value")
    @classmethod
    def finite_value(cls, value: float) -> float:
        if not math.isfinite(value):
            raise ValueError("MetricRecord value must be finite.")
        return value


class EvidenceRecord(StrictModel):
    """Server-owned synthetic or official evidence; never generated by an LLM."""

    evidence_id: Identifier
    run_id: Identifier
    document_id: Identifier
    document_sha256: Sha256
    page: int = Field(ge=1)
    excerpt: Annotated[str, Field(min_length=1, max_length=4_000)]
    period: NonEmptyText
    unit: str | None = Field(default=None, min_length=1, max_length=80)
    status: Literal["synthetic_demo_evidence", "official_corpus_passage"]
    passage_id: Identifier | None = None
    source_record_type: str | None = Field(default=None, min_length=1, max_length=80)
    source_record_id: Identifier | None = None
    issuer_id: Identifier | None = None
    publication_date: date | None = None
    printed_page: int | None = Field(default=None, ge=1)

    @model_validator(mode="after")
    def provenance_matches_status(self) -> EvidenceRecord:
        official_fields = (
            self.passage_id,
            self.source_record_type,
            self.source_record_id,
            self.issuer_id,
            self.publication_date,
        )
        if self.status == "official_corpus_passage" and any(
            value is None for value in official_fields
        ):
            raise ValueError("Official corpus evidence requires complete source provenance.")
        if self.status == "synthetic_demo_evidence" and any(
            value is not None for value in (*official_fields, self.printed_page)
        ):
            raise ValueError("Synthetic evidence cannot claim official source provenance.")
        return self


class GenerationParameter(StrictModel):
    """One provider-neutral generation parameter recorded for audit."""

    name: Identifier
    value: str | int | float | bool


class GenerationMetadata(StrictModel):
    """Provider-neutral generation parameters and optional per-attempt call metadata."""

    provider: Identifier
    model_id: Identifier
    parameters: tuple[GenerationParameter, ...]
    prompt_version: Identifier
    response_id: Annotated[str, Field(min_length=1, max_length=200)]
    generated_at: datetime
    model_call: ModelCallMetadata | None = None

    @field_validator("generated_at")
    @classmethod
    def generated_at_is_utc(cls, value: datetime) -> datetime:
        _require_utc(value, "generated_at")
        return value


class ClaimProposal(StrictModel):
    """Untrusted structured content proposed by the fake, without a claim ID."""

    text_template: Annotated[str, Field(min_length=1, max_length=1_000)]
    claim_type: ClaimType
    metric_ids: tuple[Identifier, ...] = ()
    evidence_ids: tuple[Identifier, ...] = ()
    uncertainty: str | None = Field(default=None, max_length=500)

    @model_validator(mode="after")
    def validate_reference_shape(self) -> ClaimProposal:
        if len(set(self.metric_ids)) != len(self.metric_ids):
            raise ValueError("metric_ids must be unique within a claim.")
        if len(set(self.evidence_ids)) != len(self.evidence_ids):
            raise ValueError("evidence_ids must be unique within a claim.")
        if self.claim_type == "quantitative" and not self.metric_ids:
            raise ValueError("A quantitative claim must reference at least one metric_id.")
        if self.claim_type == "evidence" and not self.evidence_ids:
            raise ValueError("An evidence claim must reference at least one evidence_id.")
        return self


class DraftProposal(StrictModel):
    """Exact structured-output schema accepted from the fake generator."""

    summary: NonEmptyText
    claims: Annotated[tuple[ClaimProposal, ...], Field(min_length=1, max_length=12)]
    limitations: Annotated[tuple[NonEmptyText, ...], Field(min_length=1, max_length=12)]


PublicFixtureLimitation = Literal[
    "editorial-redundancy-in-evidence-claim",
    "null-uncertainty-on-two-evidence-claims",
]


class PublicFixturePromotionReview(StrictModel):
    """Explicit human promotion decision, separate from a run-level HumanReview."""

    disposition: Literal["approved"] = "approved"
    review_basis: Literal["explicit-user-approval"] = "explicit-user-approval"
    reviewed_on: date
    accepted_non_blocking_limitations: tuple[PublicFixtureLimitation, ...]

    @model_validator(mode="after")
    def limitations_are_exact(self) -> PublicFixturePromotionReview:
        expected: tuple[PublicFixtureLimitation, ...] = (
            "editorial-redundancy-in-evidence-claim",
            "null-uncertainty-on-two-evidence-claims",
        )
        if self.accepted_non_blocking_limitations != expected:
            raise ValueError("Public fixture promotion must record both accepted limitations.")
        return self


class PublicDemoFixture(StrictModel):
    """Human-approved public fixture derived from a normalized live response."""

    schema_version: Literal["public-demo-fixture.v1"] = "public-demo-fixture.v1"
    status: Literal["approved_for_public_demo"] = "approved_for_public_demo"
    demo_eligible: Literal[True] = True
    promotion_policy: Literal["explicit_human_approval_recorded"] = (
        "explicit_human_approval_recorded"
    )
    fixture_derivation: Literal["live_derived_deterministically_normalized"] = (
        "live_derived_deterministically_normalized"
    )
    normalization_version: Literal["canonical-summary-v1"] = "canonical-summary-v1"
    normalized_fields: tuple[Literal["summary"], ...] = ("summary",)
    raw_provider_response_persisted: Literal[False] = False
    source_artifact_type: Literal["rejected_live_capture"] = "rejected_live_capture"
    source_artifact_sha256: Sha256
    source_candidate_schema_version: Literal["sanitized-live-capture-candidate.v1"]
    source_candidate_sha256: Sha256
    validated_input_schema_version: Literal["validated-run-input.v1"]
    validation_status: Literal["validated"] = "validated"
    render_status: Literal["reliable"] = "reliable"
    run_id: Identifier
    provider: Identifier
    model_id: NonEmptyText
    prompt_version: Literal["trust-synthesis-v3"]
    allowed_metric_ids: Annotated[tuple[Identifier, ...], Field(min_length=1)]
    evidence: Annotated[tuple[EvidenceRecord, ...], Field(min_length=1)]
    proposal: DraftProposal
    model_call: ModelCallMetadata
    promotion_review: PublicFixturePromotionReview

    @model_validator(mode="after")
    def provenance_and_allowlists_are_consistent(self) -> PublicDemoFixture:
        canonical_summary = (
            "This report presents historical run metrics and a separate official evidence "
            "record. Each is reported independently, and no temporal, causal, predictive or "
            "investment relationship between them is asserted."
        )
        if self.proposal.summary != canonical_summary:
            raise ValueError("Public fixture summary must be canonical-summary-v1.")
        if self.normalized_fields != ("summary",):
            raise ValueError("Public fixture may normalize only the summary.")
        if any(record.run_id != self.run_id for record in self.evidence):
            raise ValueError("Every public fixture evidence record must belong to its run.")
        if any(record.status != "official_corpus_passage" for record in self.evidence):
            raise ValueError("Public fixture evidence must come from the official corpus.")
        metric_ids = {
            metric_id for claim in self.proposal.claims for metric_id in claim.metric_ids
        }
        evidence_ids = {
            evidence_id for claim in self.proposal.claims for evidence_id in claim.evidence_ids
        }
        if metric_ids != set(self.allowed_metric_ids):
            raise ValueError("Public fixture metric references must match its allowlist.")
        if evidence_ids != {record.evidence_id for record in self.evidence}:
            raise ValueError("Public fixture evidence references must match its records.")
        evidence_claims = tuple(
            claim for claim in self.proposal.claims if claim.claim_type == "evidence"
        )
        if sum(claim.uncertainty is None for claim in evidence_claims) != 2:
            raise ValueError("Public fixture must retain the two accepted null uncertainties.")
        if sum(
            "reports a zero value explicitly reported" in claim.text_template
            for claim in evidence_claims
        ) != 1:
            raise ValueError("Public fixture must retain the accepted editorial redundancy.")
        if len(set(self.allowed_metric_ids)) != len(self.allowed_metric_ids):
            raise ValueError("Public fixture metric allowlist must be unique.")
        if (
            self.model_call.provider != self.provider
            or self.model_call.model_id != self.model_id
            or self.model_call.prompt_version != self.prompt_version
        ):
            raise ValueError("Public fixture identity must match its live call metadata.")
        if self.model_call.response_origin != "live_provider":
            raise ValueError("Public fixture must retain its live provider origin.")
        if self.model_call.status != "schema_error":
            raise ValueError("Public fixture must retain the historical source call status.")
        if self.model_call.response_id is None or self.model_call.provider_request_id is None:
            raise ValueError("Public fixture requires source request and response IDs.")
        return self


class ClaimDraft(StrictModel):
    """Server-materialized claim with deterministic authority-owned identity."""

    claim_id: Identifier
    run_id: Identifier
    text_template: Annotated[str, Field(min_length=1, max_length=1_000)]
    claim_type: ClaimType
    metric_ids: tuple[Identifier, ...] = ()
    evidence_ids: tuple[Identifier, ...] = ()
    uncertainty: str | None = Field(default=None, max_length=500)

    @model_validator(mode="after")
    def validate_reference_shape(self) -> ClaimDraft:
        if len(set(self.metric_ids)) != len(self.metric_ids):
            raise ValueError("metric_ids must be unique within a claim.")
        if len(set(self.evidence_ids)) != len(self.evidence_ids):
            raise ValueError("evidence_ids must be unique within a claim.")
        if self.claim_type == "quantitative" and not self.metric_ids:
            raise ValueError("A quantitative claim must reference at least one metric_id.")
        if self.claim_type == "evidence" and not self.evidence_ids:
            raise ValueError("An evidence claim must reference at least one evidence_id.")
        return self


class GeneratedDraft(StrictModel):
    """Generated narrative proposal; deliberately has no validation or approval field."""

    draft_id: Identifier
    run_id: Identifier
    summary: NonEmptyText
    claims: Annotated[tuple[ClaimDraft, ...], Field(min_length=1, max_length=12)]
    limitations: Annotated[tuple[NonEmptyText, ...], Field(min_length=1, max_length=12)]
    generation: GenerationMetadata

    @model_validator(mode="after")
    def claims_belong_to_run(self) -> GeneratedDraft:
        if len({claim.claim_id for claim in self.claims}) != len(self.claims):
            raise ValueError("claim_id values must be unique.")
        if any(claim.run_id != self.run_id for claim in self.claims):
            raise ValueError("Every claim must belong to the GeneratedDraft run.")
        return self


class ValidationIssue(StrictModel):
    """Deterministic validator output with a closed code and severity vocabulary."""

    code: IssueCode
    severity: IssueSeverity
    claim_id: Identifier | None = None
    message: NonEmptyText


class StructuredReferenceComparison(StrictModel):
    """Server-owned structured fields compared by the production validator."""

    claim_id: Identifier
    claim_key: Identifier
    reference_present: bool
    reference_claim_key: Identifier | None = None
    claim_value: Decimal | None = None
    reference_value: Decimal | None = None
    claim_unit: str | None = None
    reference_unit: str | None = None
    claim_period: str | None = None
    reference_period: str | None = None
    claim_scope2_method: ReferenceScope2Method | None = None
    reference_scope2_method: ReferenceScope2Method | None = None
    publication_date: date | None = None
    cutoff_date: date
    contradicted_by_source_id: Identifier | None = None


class StructuredValidationContext(StrictModel):
    """Optional server-owned comparison and coverage context for validate_draft."""

    comparisons: tuple[StructuredReferenceComparison, ...]
    proposed_claim_keys: tuple[Identifier, ...]
    required_claim_keys: tuple[Identifier, ...]
    forbidden_claim_keys: tuple[Identifier, ...]
    minimum_claims: int = Field(ge=1)


class ValidationReport(StrictModel):
    """Trusted validation result, distinct from generation and assessment."""

    run_id: Identifier
    draft_id: Identifier
    issues: tuple[ValidationIssue, ...]
    trusted_input_count: int = Field(ge=0)
    identifier_checks_passed: bool
    value_checks_passed: bool
    run_membership_checks_passed: bool

    @property
    def has_blocking_issues(self) -> bool:
        """Return whether any issue prevents reliable rendering."""

        return any(issue.severity in {"error", "critical"} for issue in self.issues)

    @model_validator(mode="after")
    def check_summary_flags(self) -> ValidationReport:
        expected_identifier = not any(
            issue.code in IDENTIFIER_FAILURE_CODES for issue in self.issues
        )
        expected_value = not any(
            issue.code in VALUE_FAILURE_CODES
            for issue in self.issues
        )
        expected_membership = not any(
            issue.code == "cross_run_reference" for issue in self.issues
        )
        if self.identifier_checks_passed != expected_identifier:
            raise ValueError("identifier_checks_passed contradicts the issue list.")
        if self.value_checks_passed != expected_value:
            raise ValueError("value_checks_passed contradicts the issue list.")
        if self.run_membership_checks_passed != expected_membership:
            raise ValueError("run_membership_checks_passed contradicts the issue list.")
        return self


class ClaimMetricReference(StrictModel):
    """Python-created link from a claim to its authoritative rendered metric."""

    run_id: Identifier
    claim_id: Identifier
    metric_id: Identifier
    rendered_value: NonEmptyText
    unit: NonEmptyText
    transformation: Literal["none", "rounded", "percentage"]


class ClaimEvidenceReference(StrictModel):
    """Python-created link from a claim to server-owned evidence."""

    run_id: Identifier
    claim_id: Identifier
    evidence_id: Identifier


class RenderedClaim(StrictModel):
    """Claim text after Python has injected trusted numeric values."""

    run_id: Identifier
    claim_id: Identifier
    text: NonEmptyText
    metric_references: tuple[ClaimMetricReference, ...]
    evidence_references: tuple[ClaimEvidenceReference, ...]

    @model_validator(mode="after")
    def references_belong_to_claim(self) -> RenderedClaim:
        references = (*self.metric_references, *self.evidence_references)
        if any(reference.run_id != self.run_id for reference in references):
            raise ValueError("Every rendered reference must belong to the rendered run.")
        if any(reference.claim_id != self.claim_id for reference in references):
            raise ValueError("Every rendered reference must belong to the rendered claim.")
        return self


class RenderedDraft(StrictModel):
    """Reliable rendering exists only when deterministic validation succeeds."""

    run_id: Identifier
    draft_id: Identifier
    reliable: bool
    final_text: str | None = None
    claims: tuple[RenderedClaim, ...] = ()

    @model_validator(mode="after")
    def final_text_matches_reliability(self) -> RenderedDraft:
        if self.reliable and (not self.final_text or not self.claims):
            raise ValueError("Reliable rendering requires final text and claims.")
        if not self.reliable and (self.final_text is not None or self.claims):
            raise ValueError("Blocked rendering cannot emit final text or claims.")
        if any(claim.run_id != self.run_id for claim in self.claims):
            raise ValueError("Every rendered claim must belong to the rendered run.")
        return self


class AutomatedAssessment(StrictModel):
    """Automatic routing status; never an approval or human disposition."""

    run_id: Identifier
    status: AssessmentStatus
    reason_codes: Annotated[tuple[AssessmentReason, ...], Field(min_length=1)]

    @model_validator(mode="after")
    def reason_matches_status(self) -> AutomatedAssessment:
        expected: dict[AssessmentStatus, AssessmentReason] = {
            "eligible_for_review": "validated_references",
            "review_required": "blocking_validation_issues",
            "abstain": "insufficient_trusted_inputs",
        }
        if self.reason_codes != (expected[self.status],):
            raise ValueError("Assessment reason_codes must match status exactly.")
        return self


class HumanReview(StrictModel):
    """Decision created only by an explicit human action."""

    run_id: Identifier
    reviewer_id: Identifier
    comment: NonEmptyText
    reviewed_at: datetime
    disposition: HumanDisposition

    @field_validator("reviewed_at")
    @classmethod
    def reviewed_at_is_utc(cls, value: datetime) -> datetime:
        _require_utc(value, "reviewed_at")
        return value


def _require_utc(value: datetime, field_name: str) -> None:
    if value.tzinfo is None or value.utcoffset() != timedelta(0):
        raise ValueError(f"{field_name} must be timezone-aware UTC.")
