"""Strict provider-neutral contracts for Block 3 trust boundaries."""

from __future__ import annotations

import math
from datetime import datetime, timedelta
from typing import Annotated, Literal

from pydantic import BaseModel, ConfigDict, Field, field_validator, model_validator

Identifier = Annotated[
    str,
    Field(min_length=3, max_length=160, pattern=r"^[a-z][a-z0-9]*(?:-[a-z0-9]+)*$"),
]
Sha256 = Annotated[str, Field(pattern=r"^[0-9a-f]{64}$")]
NonEmptyText = Annotated[str, Field(min_length=1, max_length=2_000)]

ClaimType = Literal["quantitative", "evidence", "limitation"]
IssueCode = Literal[
    "unknown_metric",
    "unknown_evidence",
    "cross_run_reference",
    "free_numeric_literal",
    "metric_placeholder_mismatch",
    "evidence_reference_mismatch",
]
IssueSeverity = Literal["info", "warning", "error", "critical"]
AssessmentStatus = Literal["eligible_for_review", "review_required", "abstain"]
AssessmentReason = Literal[
    "validated_references",
    "blocking_validation_issues",
    "insufficient_trusted_inputs",
]
HumanDisposition = Literal["approved", "corrected", "rejected", "escalated"]
RunState = Literal["created", "generated", "validated", "pending_review", "finalized"]


class StrictModel(BaseModel):
    """Base contract: immutable, strict and closed to unknown fields."""

    model_config = ConfigDict(extra="forbid", frozen=True, strict=True)


class MetricRecord(StrictModel):
    """Authoritative numeric record created only by Python from QuantAnalysis."""

    metric_id: Identifier
    run_id: Identifier
    metric_name: Identifier
    value: float
    unit: NonEmptyText
    horizon_or_frequency: NonEmptyText
    formula_version: NonEmptyText
    snapshot_id: Identifier

    @field_validator("value")
    @classmethod
    def finite_value(cls, value: float) -> float:
        if not math.isfinite(value):
            raise ValueError("MetricRecord value must be finite.")
        return value


class EvidenceRecord(StrictModel):
    """Server fixture evidence; never generated by the fake LLM."""

    evidence_id: Identifier
    run_id: Identifier
    document_id: Identifier
    document_sha256: Sha256
    page: int = Field(ge=1)
    excerpt: Annotated[str, Field(min_length=1, max_length=280)]
    period: NonEmptyText
    unit: str | None = Field(default=None, min_length=1, max_length=80)
    status: Literal["synthetic_demo_evidence"]


class GenerationParameter(StrictModel):
    """One provider-neutral generation parameter recorded for audit."""

    name: Identifier
    value: str | int | float | bool


class GenerationMetadata(StrictModel):
    """Metadata reserved for a future real structured-generation call."""

    provider: Identifier
    model_id: Identifier
    parameters: tuple[GenerationParameter, ...]
    prompt_version: Identifier
    response_id: Identifier
    generated_at: datetime

    @field_validator("generated_at")
    @classmethod
    def generated_at_is_utc(cls, value: datetime) -> datetime:
        _require_utc(value, "generated_at")
        return value


class ClaimProposal(StrictModel):
    """Untrusted structured content proposed by the fake, without a claim ID."""

    text_template: Annotated[str, Field(min_length=1, max_length=1_000)]
    claim_type: ClaimType
    metric_ids: tuple[Identifier, ...] = ()
    evidence_ids: tuple[Identifier, ...] = ()
    uncertainty: str | None = Field(default=None, max_length=500)

    @model_validator(mode="after")
    def validate_reference_shape(self) -> ClaimProposal:
        if len(set(self.metric_ids)) != len(self.metric_ids):
            raise ValueError("metric_ids must be unique within a claim.")
        if len(set(self.evidence_ids)) != len(self.evidence_ids):
            raise ValueError("evidence_ids must be unique within a claim.")
        if self.claim_type == "quantitative" and not self.metric_ids:
            raise ValueError("A quantitative claim must reference at least one metric_id.")
        if self.claim_type == "evidence" and not self.evidence_ids:
            raise ValueError("An evidence claim must reference at least one evidence_id.")
        return self


class DraftProposal(StrictModel):
    """Exact structured-output schema accepted from the fake generator."""

    summary: NonEmptyText
    claims: Annotated[tuple[ClaimProposal, ...], Field(min_length=1, max_length=12)]
    limitations: Annotated[tuple[NonEmptyText, ...], Field(min_length=1, max_length=12)]


class ClaimDraft(StrictModel):
    """Server-materialized claim with deterministic authority-owned identity."""

    claim_id: Identifier
    run_id: Identifier
    text_template: Annotated[str, Field(min_length=1, max_length=1_000)]
    claim_type: ClaimType
    metric_ids: tuple[Identifier, ...] = ()
    evidence_ids: tuple[Identifier, ...] = ()
    uncertainty: str | None = Field(default=None, max_length=500)

    @model_validator(mode="after")
    def validate_reference_shape(self) -> ClaimDraft:
        if len(set(self.metric_ids)) != len(self.metric_ids):
            raise ValueError("metric_ids must be unique within a claim.")
        if len(set(self.evidence_ids)) != len(self.evidence_ids):
            raise ValueError("evidence_ids must be unique within a claim.")
        if self.claim_type == "quantitative" and not self.metric_ids:
            raise ValueError("A quantitative claim must reference at least one metric_id.")
        if self.claim_type == "evidence" and not self.evidence_ids:
            raise ValueError("An evidence claim must reference at least one evidence_id.")
        return self


class GeneratedDraft(StrictModel):
    """Generated narrative proposal; deliberately has no validation or approval field."""

    draft_id: Identifier
    run_id: Identifier
    summary: NonEmptyText
    claims: Annotated[tuple[ClaimDraft, ...], Field(min_length=1, max_length=12)]
    limitations: Annotated[tuple[NonEmptyText, ...], Field(min_length=1, max_length=12)]
    generation: GenerationMetadata

    @model_validator(mode="after")
    def claims_belong_to_run(self) -> GeneratedDraft:
        if len({claim.claim_id for claim in self.claims}) != len(self.claims):
            raise ValueError("claim_id values must be unique.")
        if any(claim.run_id != self.run_id for claim in self.claims):
            raise ValueError("Every claim must belong to the GeneratedDraft run.")
        return self


class ValidationIssue(StrictModel):
    """Deterministic validator output with a closed code and severity vocabulary."""

    code: IssueCode
    severity: IssueSeverity
    claim_id: Identifier | None = None
    message: NonEmptyText


class ValidationReport(StrictModel):
    """Trusted validation result, distinct from generation and assessment."""

    run_id: Identifier
    draft_id: Identifier
    issues: tuple[ValidationIssue, ...]
    identifier_checks_passed: bool
    value_checks_passed: bool
    run_membership_checks_passed: bool

    @property
    def has_blocking_issues(self) -> bool:
        """Return whether any issue prevents reliable rendering."""

        return any(issue.severity in {"error", "critical"} for issue in self.issues)

    @model_validator(mode="after")
    def check_summary_flags(self) -> ValidationReport:
        identifier_codes = {
            "unknown_metric",
            "unknown_evidence",
            "metric_placeholder_mismatch",
            "evidence_reference_mismatch",
        }
        expected_identifier = not any(
            issue.code in identifier_codes for issue in self.issues
        )
        expected_value = not any(
            issue.code == "free_numeric_literal" for issue in self.issues
        )
        expected_membership = not any(
            issue.code == "cross_run_reference" for issue in self.issues
        )
        if self.identifier_checks_passed != expected_identifier:
            raise ValueError("identifier_checks_passed contradicts the issue list.")
        if self.value_checks_passed != expected_value:
            raise ValueError("value_checks_passed contradicts the issue list.")
        if self.run_membership_checks_passed != expected_membership:
            raise ValueError("run_membership_checks_passed contradicts the issue list.")
        return self


class ClaimMetricReference(StrictModel):
    """Python-created link from a claim to its authoritative rendered metric."""

    run_id: Identifier
    claim_id: Identifier
    metric_id: Identifier
    rendered_value: NonEmptyText
    unit: NonEmptyText
    transformation: Literal["none", "rounded", "percentage"]


class ClaimEvidenceReference(StrictModel):
    """Python-created link from a claim to server-owned evidence."""

    run_id: Identifier
    claim_id: Identifier
    evidence_id: Identifier


class RenderedClaim(StrictModel):
    """Claim text after Python has injected trusted numeric values."""

    run_id: Identifier
    claim_id: Identifier
    text: NonEmptyText
    metric_references: tuple[ClaimMetricReference, ...]
    evidence_references: tuple[ClaimEvidenceReference, ...]

    @model_validator(mode="after")
    def references_belong_to_claim(self) -> RenderedClaim:
        references = (*self.metric_references, *self.evidence_references)
        if any(reference.run_id != self.run_id for reference in references):
            raise ValueError("Every rendered reference must belong to the rendered run.")
        if any(reference.claim_id != self.claim_id for reference in references):
            raise ValueError("Every rendered reference must belong to the rendered claim.")
        return self


class RenderedDraft(StrictModel):
    """Reliable rendering exists only when deterministic validation succeeds."""

    run_id: Identifier
    draft_id: Identifier
    reliable: bool
    final_text: str | None = None
    claims: tuple[RenderedClaim, ...] = ()

    @model_validator(mode="after")
    def final_text_matches_reliability(self) -> RenderedDraft:
        if self.reliable and (not self.final_text or not self.claims):
            raise ValueError("Reliable rendering requires final text and claims.")
        if not self.reliable and (self.final_text is not None or self.claims):
            raise ValueError("Blocked rendering cannot emit final text or claims.")
        if any(claim.run_id != self.run_id for claim in self.claims):
            raise ValueError("Every rendered claim must belong to the rendered run.")
        return self


class AutomatedAssessment(StrictModel):
    """Automatic routing status; never an approval or human disposition."""

    run_id: Identifier
    status: AssessmentStatus
    reason_codes: Annotated[tuple[AssessmentReason, ...], Field(min_length=1)]

    @model_validator(mode="after")
    def reason_matches_status(self) -> AutomatedAssessment:
        expected: dict[AssessmentStatus, AssessmentReason] = {
            "eligible_for_review": "validated_references",
            "review_required": "blocking_validation_issues",
            "abstain": "insufficient_trusted_inputs",
        }
        if self.reason_codes != (expected[self.status],):
            raise ValueError("Assessment reason_codes must match status exactly.")
        return self


class HumanReview(StrictModel):
    """Decision created only by an explicit human action."""

    run_id: Identifier
    reviewer_id: Identifier
    comment: NonEmptyText
    reviewed_at: datetime
    disposition: HumanDisposition

    @field_validator("reviewed_at")
    @classmethod
    def reviewed_at_is_utc(cls, value: datetime) -> datetime:
        _require_utc(value, "reviewed_at")
        return value


def _require_utc(value: datetime, field_name: str) -> None:
    if value.tzinfo is None or value.utcoffset() != timedelta(0):
        raise ValueError(f"{field_name} must be timezone-aware UTC.")
